# Пример конфига для supervisorctl
[program:dj_bot]
directory=/path/to/FileStorageTGBot/
command=python3.11 -u main.py
environment=PYTHONUNBUFFERED="1"

autostart=True
autorestart=True

stderr_logfile=/path/to/FileStorageTGBot/tgbot/data/sv_log_err.log
stderr_logfile_maxbytes=50MB
stdout_logfile=/path/to/FileStorageTGBot/tgbot/data/sv_log_out.log
stdout_logfile_maxbytes=50MB
