services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./tgbot/data:/app/tgbot/data
    stop_grace_period: 30s
